### PR TITLE
favicon, page titles for SEO, link to Perl.org

### PR DESCRIPTION
**Pull request by OpossumPetya**
* replace favicon with SVG version
* add link to perl.org in the footer
* append "Perl White Camel Awards" to the titles of individual pages of awardees. this is better for SEO, and more informative in tabs, tab hovers, and tab previews

### CODE REVIEW

**Comment by szabgab** [comment]
Thank you!

Maybe the favicon should be the image of the award itself and it might be nice to have an image of it on the site as well.

**Comment by OpossumPetya** [comment]
> Maybe the favicon should be the image of the award itself

I have an idea, will see if I can do it..

> it might be nice to have an image of it on the site as well

there are like NO images of the award on the internet! I got a few screenshots from the youtube videos, but quality is very poor. I'll ask in the Facebook group, maybe one of the fine people who got the award can take a good pic of it

**Comment by szabgab** [comment]
I have one in the living room, but it has my name on it with a spelling error :smile: 

Maybe @makotots can help us with an image of the award - without any name on it.

**Comment by OpossumPetya** [comment]
I'm so stupid and ashamed -- you ARE the award winner! I totally forgot, and that's after I was mostly checking individual people pages on you, because you have everything - main link, profiles, etc :)

**Comment by makotots** [comment]
I asked the vendor if they can help. 

Here is how the award looks, although it's not useful for this purpose. https://www.flickr.com/photos/wendyga/13366067015/in/album-72157642816609433/

**Comment by makotots** [comment]
The vendor got in touch with me however I think we can just use what Gabor has. Sent detailed info to Gabor.

**Comment by szabgab** [comment]
I've added the image received from @makotots as `docs/img/white_camel.jpg`

**Pull request merged**
